/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBinsRouteImport } from './routes/api/bins'
import { Route as ApiBinUpdateStatusRouteImport } from './routes/api/bin.updateStatus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinsRoute = ApiBinsRouteImport.update({
  id: '/api/bins',
  path: '/api/bins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinUpdateStatusRoute = ApiBinUpdateStatusRouteImport.update({
  id: '/api/bin/updateStatus',
  path: '/api/bin/updateStatus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/bin/updateStatus': typeof ApiBinUpdateStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/bin/updateStatus': typeof ApiBinUpdateStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bins': typeof ApiBinsRoute
  '/api/bin/updateStatus': typeof ApiBinUpdateStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/bins' | '/api/bin/updateStatus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/bins' | '/api/bin/updateStatus'
  id: '__root__' | '/' | '/api/bins' | '/api/bin/updateStatus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBinsRoute: typeof ApiBinsRoute
  ApiBinUpdateStatusRoute: typeof ApiBinUpdateStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bins': {
      id: '/api/bins'
      path: '/api/bins'
      fullPath: '/api/bins'
      preLoaderRoute: typeof ApiBinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bin/updateStatus': {
      id: '/api/bin/updateStatus'
      path: '/api/bin/updateStatus'
      fullPath: '/api/bin/updateStatus'
      preLoaderRoute: typeof ApiBinUpdateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBinsRoute: ApiBinsRoute,
  ApiBinUpdateStatusRoute: ApiBinUpdateStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
